/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include <inttypes.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Number of characters displayed per line of array data */
#define NUM_BYTES_PER_LINE      (16u)

/* Base address offset of inactive bank on dual bank mode */
#define INACTIVE_BANK_OFFSET    (0x2000000ul)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Array data to represent bank switching status (A) */
CY_SECTION(".rodata2a") __attribute__((used))
const uint8_t ARRAY_BANK_A[] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

/* Array data to represent bank switching status (B) */
CY_SECTION(".rodata2b") __attribute__((used))
const uint8_t ARRAY_BANK_B[] = {0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: print_Array
 * Summary:
 *  Prints the content of the buffer to the UART console.
 * Parameters:
 *  buf - buffer to print on the console.
 *  size - size of the buffer.
 * Return:
 *  none
 **********************************************************************************************************************
 */
void print_Array(uint8_t *buf, uint32_t size)
{
    printf("\r\n0x%08lx (%"PRIu32" bytes):\r\n", (uint32_t)buf, size);
    printf("-------------------------\r\n");

    for (uint32_t index = 0; index < size; index++)
    {
        printf("0x%02X ", buf[index]);

        if (0u == ((index + 1) % NUM_BYTES_PER_LINE))
        {
            printf("\r\n");
        }
    }
}

/**********************************************************************************************************************
 * Function Name: print_Bank_Status
 * Summary:
 *  Prints bank information.
 * Parameters:
 *  bankMode - current bank mode (single or dual)
 *  mapType - current mapping if mode is dual
 * Return:
 *  none
 **********************************************************************************************************************
 */
void print_Bank_Status(cy_en_bankmode_t bankMode, cy_en_maptype_t  mapType)
{
    uint8_t *ptrA = (uint8_t *)ARRAY_BANK_A;
    uint8_t *ptrB = (uint8_t *)ARRAY_BANK_B;
    uint8_t *ptrC = ptrA + INACTIVE_BANK_OFFSET;

    printf("\r\n====current bank status: ");
    if (bankMode == CY_FLASH_SINGLE_BANK_MODE)
    {
        printf("Single====\r\n");
        print_Array(ptrA, 16);
        print_Array(ptrB, 16);
    }
    else
    {
        printf("Dual(%s)====\r\n", (mapType == CY_FLASH_MAPPING_A ? "A" : "B"));
        print_Array(ptrA, 16);
        print_Array(ptrC, 16);
    }
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t result;
    bool btnState, btnStateNew;

#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdtObj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    result = cyhal_wdt_init(&wdtObj, cyhal_wdt_get_max_timeout_ms());
    CY_ASSERT(CY_RSLT_SUCCESS == result);
    cyhal_wdt_free(&wdtObj);
#endif /* #if defined (CY_DEVICE_SECURE) */

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    
    /* Board init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX,
                                 CY_RETARGET_IO_BAUDRATE);

    /* retarget-io init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize the User Button */
    if (cyhal_gpio_init(CYBSP_USER_BTN, CYHAL_GPIO_DIR_INPUT,
                              CYHAL_GPIO_DRIVE_PULLUP, CYBSP_BTN_OFF) != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* GPIO init failed. Stop program execution */
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "FLASH Dual Bank Switching code example "
           "****************** \r\n\n");

    printf("Press USER_BTN to change the mode\r\n"
           "(Single Bank -> Dual Bank(Bank A) -> Dual Bank(Bank B) -> Single Bank ->...)\r\n ");

    btnState = cyhal_gpio_read(CYBSP_USER_BTN);

    for (;;)
    {
        /* Get current bank mode */
        cy_en_bankmode_t bankMode = Cy_Flashc_GetMainBankMode();
        cy_en_maptype_t  mapType = (cy_en_maptype_t)_FLD2VAL(FLASHC_FLASH_CTL_MAIN_MAP, FLASHC_FLASH_CTL);

        /* Display the info to the terminal */
        print_Bank_Status(bankMode, mapType);

        /* Loop until the user button is pressed */
        for (;;)
        {
            if ((btnStateNew = cyhal_gpio_read(CYBSP_USER_BTN)) != btnState)
            {
                btnState = btnStateNew;

                if (btnState == CYBSP_BTN_PRESSED)
                {
                    printf("\r\nbutton is pushed\r\n");
                    if (bankMode == CY_FLASH_SINGLE_BANK_MODE)
                    {
                        /* Transit to DualBank (Bank A) mode */
                        FLASHC_FLASH_CTL &= ~FLASHC_FLASH_CTL_MAIN_MAP_Msk;
                        FLASHC_FLASH_CTL |= (1 << FLASHC_FLASH_CTL_MAIN_BANK_MODE_Pos);
                    }
                    else
                    {
                        if (mapType == CY_FLASH_MAPPING_A)
                        {
                            /* Transit to DualBank (Bank B) mode */
                            FLASHC_FLASH_CTL |= (1 << FLASHC_FLASH_CTL_MAIN_MAP_Pos);
                        }
                        else
                        {
                            /* Transit to SingleBank mode */
                            FLASHC_FLASH_CTL &= ~FLASHC_FLASH_CTL_MAIN_BANK_MODE_Msk;
                        }
                    }
                    /* Read back the register to ensure that the write operation has reached */
                    (void)FLASHC_FLASH_CTL;

                    /* Instruction barrier operation */
                    __ISB();

                    /* Invalidate cache and buffers */
                    FLASHC_FLASH_CMD |= (1 << FLASHC_FLASH_CMD_INV_Pos);
                    while (_FLD2VAL(FLASHC_FLASH_CMD_INV, FLASHC_FLASH_CMD) != 0)
                    {
                    	;
                    }

                    break;
                }
            }
        }
    }
}

/* [] END OF FILE */
